# Use uma imagem oficial leve do Python
FROM python:3.11-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      libpq-dev \
 && rm -rf /var/lib/apt/lists/*

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de dependências e instale
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie o restante da aplicação
COPY app/ ./app

# Exponha a porta em que o serviço irá rodar
EXPOSE 8001

# Comando padrão para iniciar o listener
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]